spring:
  main:
    allow-circular-references: TRUE
  data:
      mongodb:
        uri: mongodb+srv://admin:54321@cluster0.sfl39bt.mongodb.net/?retryWrites=true&w=majority
        database: meli
proxy:
  max:
    path: 20000
    method: 20000
    ip: 50000
  route:
    meli: https://api.mercadolibre.com/
    test: http://api.countrylayer.com/
    test2: https://reqres.in/